# Tarea 2 - Selección, limpieza y alistamiento de datos

**Rol:** Ingeniería de datos / Despliegue y Mantenimiento

**Integrante:** Jhoiner Javier Ramos Ramirez

## Pregunta de negocio 1

**Pregunta:**

¿En qué proveedores, modalidades y tipos de contrato se concentra la contratación de INVIAS, y existen patrones de concentración que requieran seguimiento por parte de la Dirección y los organismos de control?

## Objetivo

Preparar y alistar el conjunto de datos correspondiente a los contratos de INVIAS para realizar posteriormente el análisis descriptivo orientado a identificar la concentración de la contratación por proveedor, modalidad de contratación y tipo de contrato, así como los patrones que puedan requerir seguimiento.

## Etapas

1. Auditoría inicial de los datos.

2. Selección de variables relevantes.

3. Identificación y tratamiento de datos faltantes.

4. Identificación y tratamiento de duplicados e inconsistencias.

5. Transformación y estandarización de variables.

6. Creación de indicadores analíticos de concentración.

7. Generación del conjunto de datos final para el análisis.

## 1. Auditoría inicial de los datos

En esta etapa se verifica la estructura general del conjunto de datos
correspondiente a los contratos de INVIAS, identificando el número de
registros, variables disponibles, valores faltantes, posibles
inconsistencias y características relevantes para el análisis de
concentración contractual.

En esta etapa no se eliminan ni modifican registros. Los resultados
servirán como insumo para definir posteriormente las reglas de limpieza
y alistamiento.

In [ ]:
# Importamos las librerías necesarias

import pandas as pd
import numpy as np
import os

In [ ]:
# Verificamos el directorio de trabajo actual

print("Directorio actual:")
print(os.getcwd())

Directorio actual:
/content

In [ ]:
# Cargamos la base original de contratos de INVIAS

df = pd.read_csv(
    "invias.csv",
    low_memory=False
)

print("Base cargada correctamente.")

Base cargada correctamente.

### 1.1 Dimensiones del conjunto de datos

Se verifica inicialmente el número de registros y variables disponibles
en el conjunto de datos de INVIAS. Esta revisión permite conocer la
dimensión del dataset antes de realizar cualquier transformación,
limpieza o selección de registros.

In [ ]:
# Revisamos las dimensiones generales del conjunto de datos

print("Número de registros:", df.shape[0])
print("Número de variables:", df.shape[1])

Número de registros: 25605
Número de variables: 89

#### Hallazgo

El conjunto de datos contiene 25.605 registros y 89 variables. Esta
dimensión permite realizar el análisis a nivel contractual manteniendo
información suficiente para estudiar la concentración de la contratación
de INVIAS por proveedor, modalidad y tipo de contrato.

Para esta etapa se conserva la totalidad de los registros y variables,
debido a que todavía no se han definido criterios de exclusión o
transformación.

### 1.2 Exploración general de las variables

Se revisan los nombres y tipos de datos de las variables disponibles con
el propósito de conocer la estructura del conjunto de datos e identificar
las variables necesarias para responder la Pregunta de Negocio 1.

In [ ]:
# Revisamos nombres, tipos de datos y cantidad de valores disponibles

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25605 entries, 0 to 25604
Data columns (total 89 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   id                                                                25605 non-null  object
 1   version                                                           25605 non-null  object
 2   created_at                                                        25605 non-null  object
 3   updated_at                                                        25605 non-null  object
 4   nombre_entidad                                                    25605 non-null  object
 5   nit_entidad                                                       25605 non-null  int64
 6   departamento                                                      25605 non-null  object
 7   ciudad                                                            25605 non-null  object
 8   localizacion                                                      25605 non-null  object
 9   orden                                                             25605 non-null  object
 10  sector                                                            25605 non-null  object
 11  rama                                                              25605 non-null  object
 12  entidad_centralizada                                              25605 non-null  object
 13  proceso_de_compra                                                 25605 non-null  object
 14  id_contrato                                                       25605 non-null  object
 15  referencia_del_contrato                                           25605 non-null  object
 16  estado_contrato                                                   25605 non-null  object
 17  codigo_de_categoria_principal                                     25605 non-null  object
 18  descripcion_del_proceso                                           20718 non-null  object
 19  tipo_de_contrato                                                  20718 non-null  object
 20  modalidad_de_contratacion                                         20718 non-null  object
 21  justificacion_modalidad_de                                        20718 non-null  object
 22  fecha_de_firma                                                    17477 non-null  object
 23  fecha_de_inicio_del_contrato                                      17795 non-null  object
 24  fecha_de_fin_del_contrato                                         20074 non-null  object
 25  condiciones_de_entrega                                            20718 non-null  object
 26  tipodocproveedor                                                  20718 non-null  object
 27  documento_proveedor                                               20715 non-null  object
 28  proveedor_adjudicado                                              20718 non-null  object
 29  es_grupo                                                          20718 non-null  object
 30  es_pyme                                                           20718 non-null  object
 31  habilita_pago_adelantado                                          20718 non-null  object
 32  liquidacion                                                       20718 non-null  object
 33  obligacion_ambiental                                              20718 non-null  object
 34  obligaciones_postconsumo                                          20718 non-null  object
 35  reversion                                                         20718 non-null  object
 36  origen_de_los_recursos                                            20718 non-null  object
 37  destino_gasto                                                     20718 non-null  object
 38  valor_del_contrato                                                20718 non-null  float64
 39  valor_de_pago_adelantado                                          20718 non-null  float64
 40  valor_facturado                                                   20718 non-null  float64
 41  valor_pendiente_de_pago                                           20718 non-null  float64
 42  valor_pagado                                                      20718 non-null  float64
 43  valor_amortizado                                                  20718 non-null  float64
 44  valor_pendiente_de                                                20718 non-null  float64
 45  valor_pendiente_de_ejecucion                                      20718 non-null  float64
 46  saldo_cdp                                                         20718 non-null  float64
 47  saldo_vigencia                                                    20718 non-null  float64
 48  espostconflicto                                                   20718 non-null  object
 49  dias_adicionados                                                  20718 non-null  float64
 50  puntos_del_acuerdo                                                20718 non-null  object
 51  pilares_del_acuerdo                                               20718 non-null  object
 52  urlproceso                                                        20718 non-null  object
 53  nombre_representante_legal                                        20718 non-null  object
 54  nacionalidad_representante_legal                                  20718 non-null  object
 55  domicilio_representante_legal                                     20718 non-null  object
 56  tipo_de_identificaci_n_representante_legal                        20718 non-null  object
 57  identificaci_n_representante_legal                                20718 non-null  object
 58  genero_representante_legal                                        20718 non-null  object
 59  presupuesto_general_de_la_nacion_pgn                              20718 non-null  float64
 60  sistema_general_de_participaciones                                20718 non-null  float64
 61  sistema_general_de_regal_as                                       20718 non-null  float64
 62  recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_  20718 non-null  float64
 63  recursos_de_credito                                               20718 non-null  float64
 64  recursos_propios                                                  20718 non-null  float64
 65  ultima_actualizacion                                              14553 non-null  object
 66  codigo_entidad                                                    20718 non-null  float64
 67  codigo_proveedor                                                  20718 non-null  float64
 68  fecha_inicio_liquidacion                                          6036 non-null   object
 69  fecha_fin_liquidacion                                             6036 non-null   object
 70  objeto_del_contrato                                               20699 non-null  object
 71  duracion_del_contrato                                             20699 non-null  object
 72  nombre_del_banco                                                  20699 non-null  object
 73  tipo_de_cuenta                                                    20699 non-null  object
 74  numero_de_cuenta                                                  20699 non-null  object
 75  el_contrato_puede_ser_prorrogado                                  20699 non-null  object
 76  fecha_de_notificacion_de_prorrogacion                             2726 non-null   object
 77  nombre_ordenador_del_gasto                                        20699 non-null  object
 78  tipo_de_documento_ordenador_del_gasto                             20699 non-null  object
 79  numero_de_documento_ordenador_del_gasto                           20699 non-null  object
 80  nombre_supervisor                                                 20699 non-null  object
 81  tipo_de_documento_supervisor                                      20699 non-null  object
 82  numero_de_documento_supervisor                                    20699 non-null  object
 83  nombre_ordenador_de_pago                                          20699 non-null  object
 84  tipo_de_documento_ordenador_de_pago                               20699 non-null  object
 85  numero_de_documento_ordenador_de_pago                             20699 non-null  object
 86  documentos_tipo                                                   20699 non-null  object
 87  descripcion_documentos_tipo                                       20699 non-null  object
 88  direccion_de_ejecucion_del_contrato                               3 non-null      object
dtypes: float64(19), int64(1), object(69)
memory usage: 17.4+ MB

In [ ]:
# Mostramos todos los nombres de columnas disponibles

for i, columna in enumerate(df.columns, start=1):
    print(i, columna)

1 id
2 version
3 created_at
4 updated_at
5 nombre_entidad
6 nit_entidad
7 departamento
8 ciudad
9 localizacion
10 orden
11 sector
12 rama
13 entidad_centralizada
14 proceso_de_compra
15 id_contrato
16 referencia_del_contrato
17 estado_contrato
18 codigo_de_categoria_principal
19 descripcion_del_proceso
20 tipo_de_contrato
21 modalidad_de_contratacion
22 justificacion_modalidad_de
23 fecha_de_firma
24 fecha_de_inicio_del_contrato
25 fecha_de_fin_del_contrato
26 condiciones_de_entrega
27 tipodocproveedor
28 documento_proveedor
29 proveedor_adjudicado
30 es_grupo
31 es_pyme
32 habilita_pago_adelantado
33 liquidacion
34 obligacion_ambiental
35 obligaciones_postconsumo
36 reversion
37 origen_de_los_recursos
38 destino_gasto
39 valor_del_contrato
40 valor_de_pago_adelantado
41 valor_facturado
42 valor_pendiente_de_pago
43 valor_pagado
44 valor_amortizado
45 valor_pendiente_de
46 valor_pendiente_de_ejecucion
47 saldo_cdp
48 saldo_vigencia
49 espostconflicto
50 dias_adicionados
51 puntos_del_acuerdo
52 pilares_del_acuerdo
53 urlproceso
54 nombre_representante_legal
55 nacionalidad_representante_legal
56 domicilio_representante_legal
57 tipo_de_identificaci_n_representante_legal
58 identificaci_n_representante_legal
59 genero_representante_legal
60 presupuesto_general_de_la_nacion_pgn
61 sistema_general_de_participaciones
62 sistema_general_de_regal_as
63 recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_
64 recursos_de_credito
65 recursos_propios
66 ultima_actualizacion
67 codigo_entidad
68 codigo_proveedor
69 fecha_inicio_liquidacion
70 fecha_fin_liquidacion
71 objeto_del_contrato
72 duracion_del_contrato
73 nombre_del_banco
74 tipo_de_cuenta
75 numero_de_cuenta
76 el_contrato_puede_ser_prorrogado
77 fecha_de_notificacion_de_prorrogacion
78 nombre_ordenador_del_gasto
79 tipo_de_documento_ordenador_del_gasto
80 numero_de_documento_ordenador_del_gasto
81 nombre_supervisor
82 tipo_de_documento_supervisor
83 numero_de_documento_supervisor
84 nombre_ordenador_de_pago
85 tipo_de_documento_ordenador_de_pago
86 numero_de_documento_ordenador_de_pago
87 documentos_tipo
88 descripcion_documentos_tipo
89 direccion_de_ejecucion_del_contrato

### 1.3 Identificación de variables relevantes para la Pregunta de Negocio 1

A partir de la pregunta de negocio se identifican inicialmente las
variables relacionadas con el proveedor adjudicado, el valor contractual,
la modalidad de contratación, el tipo de contrato y algunas
características complementarias de los proveedores.

También se conservan los identificadores contractuales para verificar
la unicidad de los registros.

En esta etapa las variables se consideran candidatas. La selección
definitiva se realizará después de revisar su calidad, completitud y
consistencia.

In [ ]:
# Variables inicialmente relevantes para la Pregunta 1

variables_p1 = [
    "id_contrato",
    "referencia_del_contrato",
    "proveedor_adjudicado",
    "valor_del_contrato",
    "modalidad_de_contratacion",
    "tipo_de_contrato",
    "estado_contrato",
    "fecha_de_firma",
    "es_grupo",
    "es_pyme"
]

print("Número de variables candidatas:", len(variables_p1))

df[variables_p1].head()

Número de variables candidatas: 10

,id_contrato,referencia_del_contrato,proveedor_adjudicado,valor_del_contrato,modalidad_de_contratacion,tipo_de_contrato,estado_contrato,fecha_de_firma,es_grupo,es_pyme
0,CO1.PCCNTR.770322,000168-2019,ANGIE GERALDINE RINCÓN CALA,23500000.0,Contratación directa,Prestación de servicios,Cerrado,2019-01-29T00:00:00.000,No,No
1,CO1.PCCNTR.5481469,4028 DE 2023,Diana Catalina Burbano Delgado,15770000.0,Contratación directa,Prestación de servicios,Cerrado,2023-10-23T00:00:00.000,No,No
2,CO1.PCCNTR.6706615,3429 DE 2024,SERGIO ALEXANDER RAMIREZ YAÑES,31500000.0,Contratación directa,Prestación de servicios,Cerrado,2024-08-30T00:00:00.000,No,No
3,CO1.PCCNTR.4412417,265 DE 2023,JUAN PABLO CASTILLO VARGAS,17700000.0,Contratación directa,Prestación de servicios,En ejecución,2023-01-16T00:00:00.000,No,No
4,CO1.PCCNTR.3516681,CO1.PCCNTR.3516681,Sin Descripcion,0.0,Contratación directa,Prestación de servicios,Cancelado,NaN,No,No

In [ ]:
# Revisamos específicamente los tipos de datos de las variables seleccionadas

tipos_p1 = pd.DataFrame({
    "variable": variables_p1,
    "tipo_dato": [df[col].dtype for col in variables_p1]
})

tipos_p1

                    variable tipo_dato
0                id_contrato    object
1    referencia_del_contrato    object
2       proveedor_adjudicado    object
3         valor_del_contrato   float64
4  modalidad_de_contratacion    object
5           tipo_de_contrato    object
6            estado_contrato    object
7             fecha_de_firma    object
8                   es_grupo    object
9                    es_pyme    object

#### Hallazgo

Para la Pregunta de Negocio 1 se identificaron 10 variables candidatas.
Ocho de ellas están directamente relacionadas con el análisis de
concentración contractual: proveedor adjudicado, valor del contrato,
modalidad de contratación, tipo de contrato, estado contractual, fecha
de firma, pertenencia a grupo y condición de PYME.

Adicionalmente, se conservaron `id_contrato` y
`referencia_del_contrato` como variables de identificación, debido a que
permitirán evaluar posteriormente la unicidad de los registros y la
existencia de posibles duplicados.

La variable `valor_del_contrato` se encuentra almacenada como variable
numérica (`float64`), mientras que las demás variables seleccionadas se
encuentran inicialmente almacenadas como objetos. En etapas posteriores
será necesario transformar especialmente `fecha_de_firma` a un formato
de fecha apropiado.

### 1.4 Análisis de datos faltantes

Se analiza la completitud de las variables seleccionadas para la Pregunta
de Negocio 1. Para cada variable se calcula la cantidad de registros con
información, la cantidad de valores faltantes y su participación
porcentual.

En esta etapa no se realiza imputación ni eliminación de registros.

In [ ]:
# Calculamos cantidad y porcentaje de valores faltantes

faltantes_p1 = pd.DataFrame({
    "no_nulos": df[variables_p1].notna().sum(),
    "faltantes": df[variables_p1].isna().sum()
})

faltantes_p1["porcentaje_faltantes"] = (
    faltantes_p1["faltantes"] / len(df) * 100
)

faltantes_p1 = faltantes_p1.sort_values(
    "porcentaje_faltantes",
    ascending=False
)

faltantes_p1

                           no_nulos  faltantes  porcentaje_faltantes
fecha_de_firma                17477       8128             31.743800
proveedor_adjudicado          20718       4887             19.086116
tipo_de_contrato              20718       4887             19.086116
es_grupo                      20718       4887             19.086116
modalidad_de_contratacion     20718       4887             19.086116
valor_del_contrato            20718       4887             19.086116
es_pyme                       20718       4887             19.086116
id_contrato                   25605          0              0.000000
referencia_del_contrato       25605          0              0.000000
estado_contrato               25605          0              0.000000

#### Hallazgo

La revisión de completitud evidencia dos patrones principales de datos
faltantes.

En primer lugar, `fecha_de_firma` presenta 8.128 registros faltantes,
equivalentes al 31,74% del conjunto de datos, siendo la variable
seleccionada con mayor proporción de información ausente.

En segundo lugar, `proveedor_adjudicado`, `valor_del_contrato`,
`modalidad_de_contratacion`, `tipo_de_contrato`, `es_grupo` y
`es_pyme` presentan cada una 4.887 registros faltantes, equivalentes al
19,09% de la base.

Por el contrario, `id_contrato`, `referencia_del_contrato` y
`estado_contrato` presentan información completa para los 25.605
registros.

Debido a que varias variables presentan exactamente la misma cantidad
de datos faltantes, se requiere verificar si corresponden a los mismos
registros antes de definir cualquier estrategia de tratamiento.

### 1.5 Análisis del patrón de datos faltantes

Se observa que varias variables relevantes presentan la misma cantidad
de datos faltantes. Por esta razón se verifica si la ausencia de
información corresponde a los mismos registros.

Esta revisión permitirá determinar si existe un patrón estructural de
información incompleta dentro de la fuente de datos.

In [ ]:
# Variables que presentan potencialmente el mismo patrón de faltantes

variables_patron = [
    "proveedor_adjudicado",
    "valor_del_contrato",
    "modalidad_de_contratacion",
    "tipo_de_contrato",
    "es_grupo",
    "es_pyme"
]

# Revisamos cuántos registros tienen todas estas variables faltantes simultáneamente

patron_faltantes = df[variables_patron].isna().all(axis=1)

print(
    "Registros con todas las variables simultáneamente faltantes:",
    patron_faltantes.sum()
)

print(
    "Porcentaje:",
    round(patron_faltantes.mean() * 100, 2),
    "%"
)

Registros con todas las variables simultáneamente faltantes: 4887
Porcentaje: 19.09 %

In [ ]:
# Revisamos si los registros sin proveedor también carecen de las demás variables clave

sin_proveedor = df[df["proveedor_adjudicado"].isna()]

sin_proveedor[variables_patron].notna().sum()

proveedor_adjudicado         0
valor_del_contrato           0
modalidad_de_contratacion    0
tipo_de_contrato             0
es_grupo                     0
es_pyme                      0
dtype: int64

In [ ]:
# Revisamos el estado contractual de los registros con el patrón de faltantes

df.loc[
    patron_faltantes,
    "estado_contrato"
].value_counts(dropna=False)

estado_contrato
Cerrado              1641
Modificado           1302
En ejecución          792
terminado             470
Borrador              307
Suspendido            139
Aprobado               99
Cancelado              51
enviado Proveedor      51
cedido                 31
En aprobación           4
Name: count, dtype: int64

In [ ]:
# Observamos una muestra de estos registros

df.loc[
    patron_faltantes,
    [
        "id_contrato",
        "referencia_del_contrato",
        "estado_contrato",
        "fecha_de_firma",
        "proveedor_adjudicado",
        "valor_del_contrato"
    ]
].head(15)

,id_contrato,referencia_del_contrato,estado_contrato,fecha_de_firma,proveedor_adjudicado,valor_del_contrato
5,CO1.PCCNTR.9279238,1150-2026,Aprobado,NaN,NaN,NaN
6,CO1.PCCNTR.3241665,303-2022,Cerrado,NaN,NaN,NaN
9,CO1.PCCNTR.9272734,1141-2026,En ejecución,NaN,NaN,NaN
14,CO1.PCCNTR.3012807,1773-2021,Modificado,NaN,NaN,NaN
27,CO1.PCCNTR.8747985,2213-2025.,En ejecución,NaN,NaN,NaN
28,CO1.PCCNTR.5273883,2920-2023,terminado,NaN,NaN,NaN
31,CO1.PCCNTR.2192385,509-2021,Cerrado,NaN,NaN,NaN
37,CO1.PCCNTR.9272917,1144-2026,Borrador,NaN,NaN,NaN
38,CO1.PCCNTR.6561364,2639-2024,En ejecución,NaN,NaN,NaN
39,CO1.PCCNTR.9261166,1058-2026,Modificado,NaN,NaN,NaN
43,CO1.PCCNTR.5191385,2366 DE 2023,terminado,NaN,NaN,NaN
46,CO1.PCCNTR.6084973,0988 DE 2024,Cerrado,NaN,NaN,NaN
47,CO1.PCCNTR.5511433,4196-2023,Modificado,NaN,NaN,NaN
54,CO1.PCCNTR.5348970,3089-2023,Modificado,NaN,NaN,NaN
57,CO1.PCCNTR.6653941,3225-2024,Modificado,NaN,NaN,NaN

#### Hallazgo

El análisis conjunto de los valores faltantes confirma la existencia de
un patrón estructural de información incompleta.

Los 4.887 registros que no contienen información en
`proveedor_adjudicado` carecen simultáneamente de información en
`valor_del_contrato`, `modalidad_de_contratacion`,
`tipo_de_contrato`, `es_grupo` y `es_pyme`. Estos registros
representan aproximadamente el 19,09% del conjunto de datos.

Por lo tanto, los faltantes encontrados en estas seis variables no
deben analizarse como problemas independientes, sino como un mismo
grupo de registros con información contractual incompleta.

Adicionalmente, la ausencia de `fecha_de_firma` presenta un patrón más
amplio: existen 8.128 registros sin fecha de firma, por lo que 3.241
casos adicionales carecen de fecha aun cuando pueden disponer de
información en las demás variables principales.

En esta etapa no se eliminan estos registros. En las siguientes
secciones se analizarán sus estados contractuales y demás
características para determinar si corresponde excluirlos de la
población analítica o tratarlos de manera diferenciada.

### 1.6 Verificación de unicidad de los contratos

Se revisa la unicidad de los identificadores contractuales para
determinar si cada fila corresponde a un contrato diferente o si existen
múltiples registros asociados a un mismo contrato o referencia.

In [ ]:
# Revisamos unicidad de identificadores contractuales

print("Registros totales:", len(df))

print(
    "ID de contrato únicos:",
    df["id_contrato"].nunique()
)

print(
    "Referencias de contrato únicas:",
    df["referencia_del_contrato"].nunique()
)

Registros totales: 25605
ID de contrato únicos: 25605
Referencias de contrato únicas: 24476

In [ ]:
# Revisamos si existen filas completamente duplicadas

duplicados_exactos = df.duplicated().sum()

print("Filas completamente duplicadas:", duplicados_exactos)

Filas completamente duplicadas: 0

In [ ]:
# Identificamos referencias contractuales que aparecen más de una vez

frecuencia_referencias = (
    df["referencia_del_contrato"]
    .value_counts()
)

referencias_repetidas = frecuencia_referencias[
    frecuencia_referencias > 1
]

print(
    "Referencias contractuales repetidas:",
    len(referencias_repetidas)
)

referencias_repetidas.head(20)

Referencias contractuales repetidas: 994

referencia_del_contrato
.               12
CANCELADO        7
3655-2023        6
-                6
0                5
4616-2023        4
1913-2025        4
2408-2025        4
XXXX             4
1941 DE 2024     4
0385-2025        4
0128-2022        4
4134-2023        4
4528-2023        4
0309-2025        4
0079-2022        4
4065 DE 2024     4
0316-2025        4
4239-2023        4
468-2022         4
Name: count, dtype: int64

### 1.7 Auditoría inicial de proveedores

Debido a que el proveedor adjudicado constituye la principal unidad de
análisis para evaluar la concentración contractual, se revisa la
cantidad de proveedores registrados, los valores más frecuentes y
posibles inconsistencias en su denominación.

En esta etapa no se modifican los nombres de los proveedores.

In [ ]:
# Revisamos la cantidad de proveedores diferentes registrados

print("Proveedores únicos:",df["proveedor_adjudicado"].nunique(dropna=True))

print("Registros sin proveedor:",df["proveedor_adjudicado"].isna().sum())

Proveedores únicos: 9159
Registros sin proveedor: 4887

In [ ]:
# Proveedores con mayor número de registros

df["proveedor_adjudicado"].value_counts(dropna=False).head(20)

proveedor_adjudicado
NaN                                                            4887
Sin Descripcion                                                 791
RAFAEL HERNAN RODRIGUEZ PRIETO                                   59
RIAC SAS                                                         47
UCING SAS                                                        40
INGDECOL S.A.S.                                                  34
AMV CONSULTORES SAS                                              33
Proyectos de Ingeniería Cumbre S.A.S.                            29
CYCOV SAS                                                        28
ALBERTO RAFAEL TOLEDO VERGARA                                    28
R&R PROYECTOS DE INGENIERIA SAS                                  27
TULCAN L. J. EIVAR                                               25
MARAMBAIA NEGOCIOS A TU ALCANCE S.A.S                            24
CARLOS ALBERTO SANCHEZ LACOUTURE                                 22
ALVARO FERNANDO LARA ZAMBRANO                                    22
ASISMEDIC SAS                                                    21
FORMAS DE INGENIERIA & ARQUITECTURA S.A.S.                       21
COOPERATIVA DE TRABAJO ASOCIADO LANDAZUREÑA DE TRABAJADORES      21
S&M INGENIERIA Y ARQUITECTURA DE COLOMBIA S.A.S                  18
BRAIN INGENIERIA VIAL SAS                                        18
Name: count, dtype: int64

In [ ]:
# Revisamos posibles valores utilizados para representar información faltante

valores_especiales_proveedor = [
    "Sin Descripcion",
    "Sin Descripción",
    "No definido",
    "No Definido"
]

for valor in valores_especiales_proveedor:
    cantidad = (df["proveedor_adjudicado"].astype("string").eq(valor).sum())

    print(valor, ":", cantidad)

Sin Descripcion : 791
Sin Descripción : 0
No definido : 0
No Definido : 2

In [ ]:
# Creamos una versión temporal normalizada únicamente para diagnóstico

proveedor_original = df["proveedor_adjudicado"]

proveedor_diagnostico = (proveedor_original.astype("string").str.strip().str.upper())

print("Proveedores únicos en formato original:",proveedor_original.nunique(dropna=True))

print("Proveedores únicos después de estandarizar temporalmente","mayúsculas y espacios:",proveedor_diagnostico.nunique(dropna=True))

Proveedores únicos en formato original: 9159
Proveedores únicos después de estandarizar temporalmente mayúsculas y espacios: 9148

In [ ]:
# Identificamos nombres cuyo valor cambia al eliminar espacios externos

proveedores_con_espacios = (df["proveedor_adjudicado"].astype("string")!=df["proveedor_adjudicado"].astype("string").str.strip())

print("Registros con espacios al inicio o al final:",proveedores_con_espacios.sum())

Registros con espacios al inicio o al final: 0

### 1.8 Auditoría del valor contractual

Se analiza la distribución de `valor_del_contrato` con el propósito de
identificar valores faltantes, registros con valor cero, valores
negativos y posibles valores extremos que puedan afectar posteriormente
las medidas de concentración.

In [ ]:
# Estadísticas descriptivas del valor contractual

df["valor_del_contrato"].describe()

count    2.071800e+04
mean     4.594592e+13
std      6.403458e+15
min      0.000000e+00
25%      3.685500e+07
50%      7.258324e+07
75%      2.003976e+08
max      9.216000e+17
Name: valor_del_contrato, dtype: float64

In [ ]:
# Revisamos condiciones básicas del valor contractual

print("Valores faltantes:",df["valor_del_contrato"].isna().sum())

print("Contratos con valor igual a cero:",(df["valor_del_contrato"] == 0).sum())

print("Contratos con valor negativo:",(df["valor_del_contrato"] < 0).sum())

print("Contratos con valor positivo:",(df["valor_del_contrato"] > 0).sum())

Valores faltantes: 4887
Contratos con valor igual a cero: 1086
Contratos con valor negativo: 0
Contratos con valor positivo: 19632

In [ ]:
# Revisamos diferentes percentiles de la distribución del valor contractual

df["valor_del_contrato"].quantile([
    0,
    0.25,
    0.50,
    0.75,
    0.90,
    0.95,
    0.99,
    0.999,
    1
])

0.000    0.000000e+00
0.250    3.685500e+07
0.500    7.258324e+07
0.750    2.003976e+08
0.900    1.025014e+09
0.950    2.465544e+09
0.990    3.038492e+10
0.999    5.102165e+11
1.000    9.216000e+17
Name: valor_del_contrato, dtype: float64

In [ ]:
# Revisamos los contratos con mayor valor registrado

contratos_mayor_valor = (
    df[
        [
            "id_contrato",
            "referencia_del_contrato",
            "proveedor_adjudicado",
            "estado_contrato",
            "fecha_de_firma",
            "modalidad_de_contratacion",
            "tipo_de_contrato",
            "valor_del_contrato"
        ]
    ]
    .sort_values(
        "valor_del_contrato",
        ascending=False
    )
    .head(20)
)

contratos_mayor_valor

,id_contrato,referencia_del_contrato,proveedor_adjudicado,estado_contrato,fecha_de_firma,modalidad_de_contratacion,tipo_de_contrato,valor_del_contrato
21007,CO1.PCCNTR.2047279,1565 DE 2020,MUNICIPIO DE URIBE,Cancelado,NaN,Contratación directa,Otro,9.216000e+17
14652,CO1.PCCNTR.7506490,0551-2025,Karen Alexandra Jiménez Zubiría,Cancelado,NaN,Contratación directa,Prestación de servicios,1.112709e+16
8445,CO1.PCCNTR.3455152,745-2022,ANDREA MORENO TALEB,Cancelado,NaN,Contratación directa,Prestación de servicios,5.184000e+15
22348,CO1.PCCNTR.6589857,2880 DE 2024,Gina Paola Viloria Ramirez,Cancelado,NaN,Contratación directa,Prestación de servicios,2.809000e+15
18270,CO1.PCCNTR.5233392,----,JAIRO PERDOMO RAMIREZ,Cancelado,NaN,Contratación directa,Prestación de servicios,2.766550e+15
15629,CO1.PCCNTR.6303944,1600 DE 2024,Jhon Fredy Pachón Sanchez,Cancelado,NaN,Contratación directa,Prestación de servicios,2.453221e+15
15932,CO1.PCCNTR.3247114,372-2022,JUAN PABLO CASTILLO VARGAS,Cancelado,NaN,Contratación directa,Prestación de servicios,2.227840e+15
13328,CO1.PCCNTR.736671,100-2019,Mauricio Rodriguez Figueroa,Cancelado,NaN,Contratación directa,Prestación de servicios,2.152960e+15
7850,CO1.PCCNTR.6066474,0854 DE 2024,LAURA MARIA RAMIREZ PUENTES,Cancelado,NaN,Contratación directa,Prestación de servicios,8.122500e+14
6743,CO1.PCCNTR.4725969,868 DE 2023,Sin Descripcion,Cancelado,NaN,Contratación directa,Prestación de servicios,4.410000e+14
9109,CO1.PCCNTR.6906654,4129 DE 2024,Sin Descripcion,Borrador,NaN,Contratación directa,Prestación de servicios,2.859481e+14
20702,CO1.PCCNTR.3043705,1836-2021,MUNICIPIO DE JERICO - ANTIOQUIA,Cancelado,NaN,Contratación directa,Obra,4.914810e+12
6306,CO1.PCCNTR.2956499,1702-2021,UNION TEMPORAL PEAJES NACIONALES,Modificado,2021-10-29T00:00:00.000,Licitación pública,Concesión,1.581453e+12
21217,CO1.PCCNTR.2409882,CO1.PCCNTR.2409882,CONSORCIO CM PUTUMAYO,Cancelado,NaN,Licitación pública Obra Publica,Obra,1.151851e+12
22564,CO1.PCCNTR.5304105,NUMERO DEL CONTRATO,DIEGO ALEJANDRO PARRA DELGADO,Cancelado,NaN,Contratación directa,Suministros,1.000000e+12
15978,CO1.PCCNTR.3633179,981-2022,CONSORCIO VIADUCTO CIÉNAGA DEL MAGDALENA,Modificado,2022-05-24T00:00:00.000,Licitación pública Obra Publica,Obra,6.571764e+11
9078,CO1.PCCNTR.9496559,1397-2026,CONSORCIO VARIANTE ORIENTAL 057,Aprobado,2026-06-22T00:00:00.000,Licitación pública Obra Publica,Obra,6.503996e+11
16191,CO1.PCCNTR.2498523,1111-2021,CONSORCIO SAN FRANCISCO,Modificado,2021-06-04T00:00:00.000,Licitación pública Obra Publica,Obra,6.104614e+11
3513,CO1.PCCNTR.2410198,989-2021,CONSORCIO VIAL MHC 063,Modificado,2021-05-13T00:00:00.000,Licitación pública Obra Publica,Obra,5.933837e+11
16674,CO1.PCCNTR.2498450,964-2021,CONSTRUCCIONES EL CONDOR S.A,Modificado,2021-05-10T00:00:00.000,Licitación pública Obra Publica,Obra,5.413900e+11

### 1.9 Auditoría de modalidades de contratación

Se revisan las categorías disponibles en la variable
`modalidad_de_contratacion`, su frecuencia y la presencia de valores
faltantes o categorías poco frecuentes.

In [ ]:
# Cantidad de modalidades

print("Modalidades únicas:",df["modalidad_de_contratacion"].nunique(dropna=True))

print("Registros sin modalidad:",df["modalidad_de_contratacion"].isna().sum())

Modalidades únicas: 11
Registros sin modalidad: 4887

In [ ]:
# Distribución de registros por modalidad de contratación

df["modalidad_de_contratacion"].value_counts(dropna=False)

modalidad_de_contratacion
Contratación directa                                           14377
NaN                                                             4887
Mínima cuantía                                                  2909
Concurso de méritos abierto                                     1297
Licitación pública Obra Publica                                  787
Selección Abreviada de Menor Cuantía                             724
Licitación pública                                               429
Selección abreviada subasta inversa                              101
Seleccion Abreviada Menor Cuantia Sin Manifestacion Interes       52
Contratación Directa (con ofertas)                                33
Contratación régimen especial                                      8
Contratación régimen especial (con ofertas)                        1
Name: count, dtype: int64

### 1.10 Auditoría de tipos de contrato

Se revisan las categorías disponibles en `tipo_de_contrato` y la
frecuencia de cada una, debido a que esta variable constituye una de las
dimensiones principales del análisis de concentración.

In [ ]:
print("Tipos de contrato únicos:",df["tipo_de_contrato"].nunique(dropna=True))

print("Registros sin tipo de contrato:",df["tipo_de_contrato"].isna().sum())

df["tipo_de_contrato"].value_counts(dropna=False)

Tipos de contrato únicos: 15
Registros sin tipo de contrato: 4887

tipo_de_contrato
Prestación de servicios       12058
NaN                            4887
Obra                           3409
Otro                           2326
Interventoría                  1530
Suministros                     593
Consultoría                     573
Compraventa                      81
Comodato                         74
Seguros                          32
Arrendamiento de inmuebles       31
Acuerdo Marco de Precios          5
Decreto 092 de 2017               2
Concesión                         2
Arrendamiento de muebles          1
Servicios financieros             1
Name: count, dtype: int64

### 1.11 Auditoría del estado contractual

Se analiza la distribución del estado de los contratos para determinar
si la disponibilidad de información relacionada con proveedores,
valores contractuales y fechas presenta diferencias según el estado del
contrato.

In [ ]:
# Distribución de estados contractuales

df["estado_contrato"].value_counts(dropna=False)

estado_contrato
Cerrado              9263
Modificado           5434
terminado            3416
En ejecución         2512
Borrador             2438
Aprobado              872
Cancelado             629
Suspendido            361
enviado Proveedor     301
En aprobación         287
cedido                 92
Name: count, dtype: int64

In [ ]:
# Comparamos el estado contractual con la disponibilidad del valor del contrato

comparacion_estado_valor = pd.crosstab(df["estado_contrato"],df["valor_del_contrato"].isna(),margins=True)

comparacion_estado_valor.columns = ["valor_disponible","valor_faltante","total"]

comparacion_estado_valor

                   valor_disponible  valor_faltante  total
estado_contrato
Aprobado                        773              99    872
Borrador                       2131             307   2438
Cancelado                       578              51    629
Cerrado                        7622            1641   9263
En aprobación                   283               4    287
En ejecución                   1720             792   2512
Modificado                     4132            1302   5434
Suspendido                      222             139    361
cedido                           61              31     92
enviado Proveedor               250              51    301
terminado                      2946             470   3416
All                           20718            4887  25605

### 1.12 Auditoría de la fecha de firma

Se revisa la disponibilidad y formato de `fecha_de_firma`, debido a que
esta variable permitirá identificar contratos formalizados y estudiar la
evolución temporal de la concentración contractual.

In [ ]:
# Observamos valores originales de fecha de firma

df["fecha_de_firma"].head(10)

0    2019-01-29T00:00:00.000
1    2023-10-23T00:00:00.000
2    2024-08-30T00:00:00.000
3    2023-01-16T00:00:00.000
4                        NaN
5                        NaN
6                        NaN
7    2025-09-12T00:00:00.000
8    2023-01-19T00:00:00.000
9                        NaN
Name: fecha_de_firma, dtype: object

In [ ]:
# Creamos temporalmente una versión datetime de la fecha de firma

fecha_firma_dt = pd.to_datetime(df["fecha_de_firma"],errors="coerce")

print("Fechas originales disponibles:",df["fecha_de_firma"].notna().sum())

print("Fechas convertidas correctamente:",fecha_firma_dt.notna().sum())

print("Registros sin fecha de firma:",fecha_firma_dt.isna().sum())

Fechas originales disponibles: 17477
Fechas convertidas correctamente: 17477
Registros sin fecha de firma: 8128

In [ ]:
# Revisamos el rango de fechas disponible

print("Fecha mínima de firma:",fecha_firma_dt.min())

print("Fecha máxima de firma:",fecha_firma_dt.max())

Fecha mínima de firma: 2017-11-29 00:00:00
Fecha máxima de firma: 2026-08-06 00:00:00

In [ ]:
# Distribución preliminar de contratos por año de firma

fecha_firma_dt.dt.year.value_counts().sort_index()

fecha_de_firma
2017.0      47
2018.0    1079
2019.0    1257
2020.0    2060
2021.0    2075
2022.0    1535
2023.0    3905
2024.0    2990
2025.0    1649
2026.0     880
Name: count, dtype: int64

In [ ]:
# Revisamos disponibilidad de valor según existencia de fecha de firma

comparacion_firma_valor = pd.crosstab(fecha_firma_dt.notna(),df["valor_del_contrato"].notna(),margins=True)

comparacion_firma_valor

valor_del_contrato  False   True    All
fecha_de_firma
False                4887   3241   8128
True                    0  17477  17477
All                  4887  20718  25605

In [ ]:
# Identificamos contratos que tienen valor registrado pero no fecha de firma

sin_firma_con_valor = df[fecha_firma_dt.isna()&df["valor_del_contrato"].notna()].copy()

print("Contratos sin fecha de firma pero con valor registrado:",len(sin_firma_con_valor))

Contratos sin fecha de firma pero con valor registrado: 3241

In [ ]:
# Revisamos en qué estados se encuentran esos registros

sin_firma_con_valor["estado_contrato"].value_counts(dropna=False)

estado_contrato
Borrador             2131
Cancelado             577
En aprobación         283
enviado Proveedor     250
Name: count, dtype: int64

In [ ]:
# Revisamos los contratos sin fecha de firma con mayores valores registrados

sin_firma_con_valor[
    [
        "id_contrato",
        "referencia_del_contrato",
        "estado_contrato",
        "proveedor_adjudicado",
        "valor_del_contrato"
    ]
].sort_values("valor_del_contrato",ascending=False).head(20)

,id_contrato,referencia_del_contrato,estado_contrato,proveedor_adjudicado,valor_del_contrato
21007,CO1.PCCNTR.2047279,1565 DE 2020,Cancelado,MUNICIPIO DE URIBE,9.216000e+17
14652,CO1.PCCNTR.7506490,0551-2025,Cancelado,Karen Alexandra Jiménez Zubiría,1.112709e+16
8445,CO1.PCCNTR.3455152,745-2022,Cancelado,ANDREA MORENO TALEB,5.184000e+15
22348,CO1.PCCNTR.6589857,2880 DE 2024,Cancelado,Gina Paola Viloria Ramirez,2.809000e+15
18270,CO1.PCCNTR.5233392,----,Cancelado,JAIRO PERDOMO RAMIREZ,2.766550e+15
15629,CO1.PCCNTR.6303944,1600 DE 2024,Cancelado,Jhon Fredy Pachón Sanchez,2.453221e+15
15932,CO1.PCCNTR.3247114,372-2022,Cancelado,JUAN PABLO CASTILLO VARGAS,2.227840e+15
13328,CO1.PCCNTR.736671,100-2019,Cancelado,Mauricio Rodriguez Figueroa,2.152960e+15
7850,CO1.PCCNTR.6066474,0854 DE 2024,Cancelado,LAURA MARIA RAMIREZ PUENTES,8.122500e+14
6743,CO1.PCCNTR.4725969,868 DE 2023,Cancelado,Sin Descripcion,4.410000e+14
9109,CO1.PCCNTR.6906654,4129 DE 2024,Borrador,Sin Descripcion,2.859481e+14
20702,CO1.PCCNTR.3043705,1836-2021,Cancelado,MUNICIPIO DE JERICO - ANTIOQUIA,4.914810e+12
21217,CO1.PCCNTR.2409882,CO1.PCCNTR.2409882,Cancelado,CONSORCIO CM PUTUMAYO,1.151851e+12
22564,CO1.PCCNTR.5304105,NUMERO DEL CONTRATO,Cancelado,DIEGO ALEJANDRO PARRA DELGADO,1.000000e+12
16410,CO1.PCCNTR.9630151,CO1.PCCNTR.9630151,Borrador,CONSORCIO INMAHA GUAJIRA 063,3.977399e+11
7740,CO1.PCCNTR.8623361,1939-2025,Borrador,JUNTA DE ACCION COMUNAL DE LA VEREDA LA COQUERA,3.210000e+11
4383,CO1.PCCNTR.9630415,1467-2026,enviado Proveedor,CONSORCIO CONEXION INVIAS 063,3.012289e+11
14987,CO1.PCCNTR.9720695,CO1.PCCNTR.9720695,Borrador,CONSORCIO PROYECTOS GUAJIRA,2.807320e+11
24133,CO1.PCCNTR.9720877,CO1.PCCNTR.9720877,Borrador,CONSORCIO VIAL DE LA GUAJIRA 062,2.802781e+11
24477,CO1.PCCNTR.9721318,CO1.PCCNTR.9721318,Borrador,C. ISLA URIBIA,2.802224e+11

### 1.13 Auditoría de características del proveedor

Se revisan las variables `es_grupo` y `es_pyme`, las cuales permitirán
posteriormente segmentar la contratación y analizar si existen diferencias
en la concentración según las características del proveedor.

In [ ]:
# Distribución de la variable es_grupo

df["es_grupo"].value_counts(dropna=False)

es_grupo
No     18952
NaN     4887
Si      1766
Name: count, dtype: int64

In [ ]:
# Distribución de la variable es_pyme

df["es_pyme"].value_counts(dropna=False)

es_pyme
No     15429
Si      5289
NaN     4887
Name: count, dtype: int64

In [ ]:
# Construimos una tabla resumen de las variables principales

resumen_variables_p1 = pd.DataFrame({
    "tipo_dato": df[variables_p1].dtypes.astype(str),
    "no_nulos": df[variables_p1].notna().sum(),
    "faltantes": df[variables_p1].isna().sum(),
    "valores_unicos": df[variables_p1].nunique(dropna=True)
})

resumen_variables_p1["porcentaje_faltantes"] = (resumen_variables_p1["faltantes"]/ len(df)* 100)

resumen_variables_p1

,tipo_dato,no_nulos,faltantes,valores_unicos,porcentaje_faltantes
id_contrato,object,25605,0,25605,0.000000
referencia_del_contrato,object,25605,0,24476,0.000000
proveedor_adjudicado,object,20718,4887,9159,19.086116
valor_del_contrato,float64,20718,4887,12360,19.086116
modalidad_de_contratacion,object,20718,4887,11,19.086116
tipo_de_contrato,object,20718,4887,15,19.086116
estado_contrato,object,25605,0,11,0.000000
fecha_de_firma,object,17477,8128,1912,31.743800
es_grupo,object,20718,4887,2,19.086116
es_pyme,object,20718,4887,2,19.086116

### 1.14 Evaluación preliminar de la población analítica

Antes de definir el conjunto definitivo para el análisis, se compara la
cantidad de registros disponibles bajo diferentes criterios relacionados
con la existencia de proveedor, valor contractual positivo y fecha de
firma.

Esta evaluación es diagnóstica y no implica aún la eliminación de
registros.

In [ ]:
# Condiciones preliminares

condicion_proveedor = (df["proveedor_adjudicado"].notna())

condicion_valor_positivo = (df["valor_del_contrato"] > 0)

condicion_fecha_firma = (fecha_firma_dt.notna())

print("Registros totales:",len(df))

print("Con proveedor:",condicion_proveedor.sum())

print("Con valor positivo:",condicion_valor_positivo.sum())

print("Con fecha de firma:",condicion_fecha_firma.sum())

print("Con proveedor + valor positivo:",(condicion_proveedor& condicion_valor_positivo).sum())

print("Con proveedor + valor positivo + fecha de firma:",(condicion_proveedor& condicion_valor_positivo& condicion_fecha_firma).sum())

Registros totales: 25605
Con proveedor: 20718
Con valor positivo: 19632
Con fecha de firma: 17477
Con proveedor + valor positivo: 19632
Con proveedor + valor positivo + fecha de firma: 17244

In [ ]:
# Resumen general de los principales resultados de auditoría

resumen_auditoria = pd.DataFrame({
    "Indicador": [
        "Registros originales",
        "Variables originales",
        "ID contrato únicos",
        "Referencias únicas",
        "Proveedores únicos",
        "Registros sin proveedor",
        "Registros sin valor contractual",
        "Contratos con valor cero",
        "Contratos con valor negativo",
        "Contratos con fecha de firma",
        "Contratos sin fecha de firma",
        "Modalidades únicas",
        "Tipos de contrato únicos"
    ],

    "Resultado": [
        len(df),
        df.shape[1],
        df["id_contrato"].nunique(),
        df["referencia_del_contrato"].nunique(),
        df["proveedor_adjudicado"].nunique(dropna=True),
        df["proveedor_adjudicado"].isna().sum(),
        df["valor_del_contrato"].isna().sum(),
        (df["valor_del_contrato"] == 0).sum(),
        (df["valor_del_contrato"] < 0).sum(),
        fecha_firma_dt.notna().sum(),
        fecha_firma_dt.isna().sum(),
        df["modalidad_de_contratacion"].nunique(dropna=True),
        df["tipo_de_contrato"].nunique(dropna=True)
    ]
})

resumen_auditoria

                          Indicador  Resultado
0              Registros originales      25605
1              Variables originales         89
2                ID contrato únicos      25605
3                Referencias únicas      24476
4                Proveedores únicos       9159
5           Registros sin proveedor       4887
6   Registros sin valor contractual       4887
7          Contratos con valor cero       1086
8      Contratos con valor negativo          0
9      Contratos con fecha de firma      17477
10     Contratos sin fecha de firma       8128
11               Modalidades únicas         11
12         Tipos de contrato únicos         15

## Resumen de hallazgos de auditoría inicial

La auditoría inicial permitió evaluar la estructura, completitud y
consistencia de las variables necesarias para responder la Pregunta de
Negocio 1.

Se revisaron especialmente la identificación de proveedores, el valor
contractual, las modalidades de contratación, los tipos de contrato, los
estados contractuales y la disponibilidad de fechas de firma.

También se evaluaron posibles problemas asociados con nombres de
proveedores, valores contractuales extremos, contratos con valor cero,
registros sin fecha de firma y patrones comunes de información faltante.

Los resultados obtenidos serán utilizados en el siguiente notebook para
definir las reglas de limpieza, estandarización y selección de la
población analítica.

En esta etapa no se eliminaron ni modificaron registros.